apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: your-springboot-image:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: springboot-volume
              mountPath: /app/uploads   # direktori dalam container
      volumes:
        - name: springboot-volume
          persistentVolumeClaim:
            claimName: upload-pvc   # PVC yang sudah ada